[package]
name = "rosetta-docker"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
docker-api = "0.12.2"
env_logger = "0.10.0"
futures = "0.3.25"
getrandom = "0.2.8"
log = "0.4.17"
rosetta = { version = "0.1.0", path = "../rosetta" }
surf = { version = "2.3.2", default-features = false, features = ["h1-client-no-tls"] }
tokio = "1.24.2"

[dev-dependencies]
tokio = { version = "1.24.2", features = ["macros"] }
