[workspace]
members = [
    "dioxus-wallet",
    "rosetta-cli",
    "rosetta-client",
    "rosetta-crypto",
    "rosetta-indexer",
    "rosetta-server-polkadot",
    "rosetta-server-substrate",
    "rosetta-types",
    "rosetta-wallet",
]
resolver = "2"

[patch.crates-io]
dirs-next = { git = "https://github.com/dvc94ch/dirs", branch = "android" }
