[package]
name = "rosetta-sdk-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
rosetta-sdk-rust-gen = { path = "./core" }

[dev-dependencies]
anyhow = "1.0.64"
swagger = "6.2.1"
tokio = { version = "1.21.1", features = ["full"] }
