[workspace]
members = [
    "dioxus-wallet",
    "rosetta-cli",
    "rosetta-client",
    "rosetta-crypto",
    "rosetta-server-substrate",
    "rosetta-types",
    "rosetta-wallet",
]

[patch.crates-io]
bip39 = { git = "https://github.com/trevyn/rust-bip39", branch = "unpin-unicode-normalization" }
dioxus = { git = "https://github.com/dioxuslabs/dioxus", branch = "master" }
dioxus-desktop = { git = "https://github.com/dioxuslabs/dioxus", branch = "master" }
dioxus-web = { git = "https://github.com/dioxuslabs/dioxus", branch = "master" }
