[workspace]
members = [
  "chains/astar/config",
  "chains/astar/server",
  "chains/bitcoin/config",
  "chains/bitcoin/server",
  "chains/ethereum/config",
  "chains/ethereum/rpc-client",
  "chains/ethereum/server",
  "chains/ethereum/tx",
  "chains/polkadot/config",
  "chains/polkadot/server",
  "chains/polkadot/tx",
  "rosetta-cli",
  "rosetta-client",
  "rosetta-core",
  "rosetta-crypto",
  "rosetta-docker",
  "rosetta-server",
  "rosetta-types",
  "rosetta-wallet",
]
resolver = "2"
