[workspace]
members = [
    "dioxus-wallet",
    "rosetta-cli",
    "rosetta-client",
    "rosetta-crypto",
    "rosetta-server-substrate",
    "rosetta-types",
    "rosetta-wallet",
]

[patch.crates-io]
bardecoder = { git = "https://github.com/dvc94ch/bardecoder", branch = "fix-ios-crash" }
dioxus = { git = "https://github.com/dvc94ch/dioxus", branch = "ios-push-view" }
dioxus-desktop = { git = "https://github.com/dvc94ch/dioxus", branch = "ios-push-view" }
dioxus-router = { git = "https://github.com/dvc94ch/dioxus", branch = "ios-push-view" }
dioxus-web = { git = "https://github.com/dvc94ch/dioxus", branch = "ios-push-view" }
fermi = { git = "https://github.com/dvc94ch/dioxus", branch = "ios-push-view" }
