[workspace]
members = [
    "chains/bitcoin/config",
    "chains/bitcoin/server",
    "chains/ethereum/config",
    "chains/ethereum/server",
    "chains/polkadot/config",
    "chains/polkadot/server",
    "dioxus-wallet",
    "rosetta-cli",
    "rosetta-client",
    "rosetta-core",
    "rosetta-crypto",
    "rosetta-docker",
    "rosetta-server",
    "rosetta-types",
    "rosetta-wallet",
]
resolver = "2"

[patch.crates-io]
dioxus = { git = "https://github.com/dioxuslabs/dioxus", rev = "1e99e35" }
dioxus-desktop = { git = "https://github.com/dioxuslabs/dioxus", rev = "1e99e35" }
dioxus-router = { git = "https://github.com/dioxuslabs/dioxus", rev = "1e99e35" }
dioxus-web = { git = "https://github.com/dioxuslabs/dioxus", rev = "1e99e35" }
fermi = { git = "https://github.com/dioxuslabs/dioxus", rev = "1e99e35" }
dirs-next = { git = "https://github.com/dvc94ch/dirs", branch = "android" }
