version: "3.9"

volumes:
  bitcoin-volume:
  ethereum-volume:
  polkadot-volume:
  astar-volume:
  humanode-volume:

services:
  bitcoin:
    image: "ruimarinho/bitcoin-core:23"
    command: "-regtest=1 -rpcbind=0.0.0.0 -rpcport=18443 -rpcallowip=0.0.0.0/0 -rpcuser=rosetta -rpcpassword=rosetta"
    expose:
    - "18443"
    ulimits:
      nofile:
        soft: 10000
        hard: 10000
    deploy:
      resources:
        reservations:
          memory: 1g
    volumes:
    - "bitcoin-volume:/home/bitcoin/.bitcoin"

  ethereum:
    image: "ethereum/client-go:v1.12.2"
    command: "--dev --ipcdisable --http --http.addr 0.0.0.0 --http.vhosts * --http.api eth,debug,admin,txpool,web3"
    expose:
    - "8545"
    ulimits:
      nofile:
        soft: 10000
        hard: 10000
    deploy:
      resources:
        reservations:
          memory: 1g
    volumes:
    - "ethereum-volume:/root"

  polkadot:
    image: "parity/polkadot:v1.0.0"
    command: "--dev --rpc-external --rpc-port=9944 --alice --blocks-pruning archive --state-pruning archive --base-path /polkadot"
    expose:
    - "9944"
    user: root
    ulimits:
      nofile:
        soft: 10000
        hard: 10000
    deploy:
      resources:
        reservations:
          memory: 1g
    volumes:
    - "polkadot-volume:/polkadot"

  astar:
    image: "staketechnologies/astar-collator:v5.15.0"
    command: "astar-collator --chain dev --rpc-port=9994 --rpc-cors=all --rpc-external --alice --enable-evm-rpc --base-path /astar"
    expose:
    - "9994"
    user: root
    ulimits:
      nofile:
        soft: 10000
        hard: 10000
    deploy:
      resources:
        reservations:
          memory: 1g
    volumes:
    - "astar-volume:/astar"

  humanode:
    image: "humanode"
    command: "humanode-peer --chain dev --rpc-cors=all --ws-external --alice"
    expose:
      - "9944"
    user: root
    ulimits:
      nofile:
        soft: 10000
        hard: 10000
    deploy:
      resources:
        reservations:
          memory: 1g
    ports:
      - "9946:9946"
    volumes:
    - "humanode-volume:/humanode"


  connector-bitcoin:
    image: "analoglabs/connector-bitcoin"
    command: "--network regtest --addr 0.0.0.0:8080 --node-addr http://bitcoin:18443"
    ports:
    - "8080:8080"
    depends_on:
    - bitcoin

  connector-ethereum:
    image: "analoglabs/connector-ethereum"
    command: "--network dev --addr 0.0.0.0:8081 --node-addr http://ethereum:8545"
    ports:
    - "8081:8081"
    depends_on:
    - ethereum

  connector-polkadot:
    image: "analoglabs/connector-polkadot"
    command: "--network dev --addr 0.0.0.0:8082 --node-addr ws://polkadot:9944"
    ports:
    - "8082:8082"
    depends_on:
    - polkadot
    # TODO: need to do a proper health check
    restart: always

  connector-astar:
    image: "analoglabs/connector-astar"
    command: "--network dev --addr 0.0.0.0:8083 --node-addr ws://astar:9944"
    ports:
    - "8083:8083"
    depends_on:
    - astar
    restart: always

  connector-humanode:
    image: "humanode"
    command: "--network dev --addr 0.0.0.0:8084 --node-addr ws://humanode:9944"
    ports:
      -"8084:8084"
    depends_on:
      - humanode
    restart: always
