version: "3.9"

volumes:
  ethereum-volume:
  polkadot-volume:
  astar-volume:

services:
  ethereum:
    image: "ethereum/client-go:v1.12.2"
    command: "--dev --ipcdisable --http --http.addr 0.0.0.0 --http.vhosts * --http.api eth,debug,admin,txpool,web3"
    expose:
    - "8545"
    ulimits:
      nofile:
        soft: 10000
        hard: 10000
    deploy:
      resources:
        reservations:
          memory: 1g
    volumes:
    - "ethereum-volume:/root"
  
    polygon:
      image: "local/bor"
      command: "--dev --ipcdisable --http --http.addr 0.0.0.0 --http.vhosts * --http.api eth,debug,admin,txpool,web3"
      expose:
      - "8546"
      ulimits:
        nofile:
          soft: 10000
          hard: 10000
      deploy:
        resources:
          reservations:
            memory: 1g
      volumes:
      - "local/bor"

  polkadot:
    image: "parity/polkadot:v1.5.0"
    command: "--chain=westend-dev --dev --rpc-external --rpc-port=9944 --alice --blocks-pruning archive --state-pruning archive --base-path /polkadot"
    expose:
    - "9944"
    user: root
    ulimits:
      nofile:
        soft: 10000
        hard: 10000
    deploy:
      resources:
        reservations:
          memory: 1g
    volumes:
    - "polkadot-volume:/polkadot"

  astar:
    image: "staketechnologies/astar-collator:v5.28.0-rerun"
    command: "astar-collator --chain dev --rpc-port=9994 --rpc-cors=all --rpc-external --alice --enable-evm-rpc --base-path /astar"
    expose:
    - "9994"
    user: root
    ulimits:
      nofile:
        soft: 10000
        hard: 10000
    deploy:
      resources:
        reservations:
          memory: 1g
    volumes:
    - "astar-volume:/astar"

  connector-ethereum:
    image: "analoglabs/connector-ethereum"
    command: "--network dev --addr 0.0.0.0:8081 --node-addr http://ethereum:8545"
    ports:
    - "8081:8081"
    depends_on:
    - ethereum

  connector-polkadot:
    image: "analoglabs/connector-polkadot"
    command: "--network dev --addr 0.0.0.0:8082 --node-addr ws://polkadot:9944"
    ports:
    - "8082:8082"
    depends_on:
    - polkadot
    # TODO: need to do a proper health check
    restart: always

  connector-astar:
    image: "analoglabs/connector-astar"
    command: "--network dev --addr 0.0.0.0:8083 --node-addr ws://astar:9994"
    ports:
    - "8083:8083"
    depends_on:
    - astar
    restart: always

  connector-polygon:
    image: "local/bor"
    command: "--network dev --addr 0.0.0.0:8084 --node-addr ws://polygon:9994"
    ports:
    - "8084:8084"
    depends_on:
    - polygon
    restart: always
