version: "3.9"
services:
  bitcoin:
    image: "analoglabs/rosetta-bitcoin"
    environment:
      - NETWORK=REGTEST
      - MODE=ONLINE
      - PORT=8080
    ports:
      - "8080:8080"
      - "18333:18333"
      - "18443:18443"
  ethereum:
    image: "analoglabs/rosetta-ethereum"
    environment:
      - NETWORK=TESTNET
      - MODE=ONLINE
      - PORT=8081
    ports:
      - "8081:8081"
      - "30303:30303"
      - "8545:8545"
  rosetta-substrate:
    image: "analoglabs/rosetta-substrate"
    build:
      context: "."
      dockerfile: "./rosetta-server-substrate/Dockerfile"
    environment:
      - PORT=8082
      - NETWORK=DEV
      - NODE=ws://polkadot:9944
    ports:
      - "8082:8082"
  polkadot:
    image: "parity/polkadot:v0.9.32"
    ports:
      - "30333:30333"
  explorer:
    image: "analoglabs/rosetta-explorer"
    ports:
      - "3000:3000"
    links:
      - bitcoin
      - ethereum
      - polkadot
