version: "3.9"

volumes:
  bitcoin-volume:
  ethereum-volume:
  polkadot-volume:

services:
  bitcoin:
    image: "ruimarinho/bitcoin-core"
    command: "-regtest=1 -rpcbind=0.0.0.0 -rpcport=18443 -rpcallowip=0.0.0.0/0 -rpcuser=rosetta -rpcpassword=rosetta"
    expose:
    - "18443"
    ulimits:
      nofile:
        soft: 10000
        hard: 10000
    deploy:
      resources:
        reservations:
          memory: 1g
    volumes:
    - "bitcoin-volume:/home/bitcoin/.bitcoin"

  ethereum:
    image: "ethereum/client-go"
    command: "--dev --ipcdisable --http --http.addr 0.0.0.0 --http.vhosts * --http.api eth,debug,admin,txpool,web3"
    expose:
    - "8545"
    ulimits:
      nofile:
        soft: 10000
        hard: 10000
    deploy:
      resources:
        reservations:
          memory: 1g
    volumes:
    - "ethereum-volume:/root"

  polkadot:
    image: "parity/polkadot"
    command: "--chain dev --rpc-cors all --ws-external --alice --tmp"
    expose:
    - "9944"
    ulimits:
      nofile:
        soft: 10000
        hard: 10000
    deploy:
      resources:
        reservations:
          memory: 1g
    volumes:
    - "polkadot-volume:/polkadot"


  connector-bitcoin:
    image: "analoglabs/connector-bitcoin"
    command: "--network regtest --addr 0.0.0.0:8080 --node-addr bitcoin:18443"
    ports:
    - "8080:8080"
    depends_on:
    - bitcoin

  connector-ethereum:
    image: "analoglabs/connector-ethereum"
    command: "--network dev --addr 0.0.0.0:8081 --node-addr ethereum:8545"
    ports:
    - "8081:8081"
    depends_on:
    - ethereum

  connector-polkadot:
    image: "analoglabs/connector-polkadot"
    command: "--network dev --addr 0.0.0.0:8082 --node-addr polkadot:9944"
    ports:
    - "8082:8082"
    depends_on:
    - polkadot
    # TODO: need to do a proper health check
    restart: always


  explorer:
    image: "analoglabs/rosetta-explorer"
    ports:
    - "3000:3000"
    depends_on:
    - connector-bitcoin
    - connector-ethereum
    - connector-polkadot
