version: "3.9"

volumes:
  bitcoin-volume:
  ethereum-volume:
  polkadot-volume:

services:
  bitcoin:
    image: "ruimarinho/bitcoin-core"
    command: "-regtest=1 -rpcbind=0.0.0.0 -rpcport=18443 -rpcallowip=0.0.0.0/0 -rpcuser=rosetta -rpcpassword=rosetta"
    expose:
    - "18443"
    ulimits:
      nofile:
        soft: 10000
        hard: 10000
    deploy:
      resources:
        reservations:
          memory: 1g
    volumes:
    - "bitcoin-volume:/home/bitcoin/.bitcoin"

  ethereum:
    image: "ethereum/client-go"
    command: "--dev --ipcdisable --http --http.addr 0.0.0.0 --http.vhosts * --http.api eth,debug,admin,txpool"
    expose:
    - "8545"
    ulimits:
      nofile:
        soft: 10000
        hard: 10000
    deploy:
      resources:
        reservations:
          memory: 1g
    volumes:
    - "ethereum-volume:/root"

  polkadot:
    image: "parity/polkadot"
    command: "--chain dev --ws-external --alice --tmp"
    expose:
    - "9944"
    ulimits:
      nofile:
        soft: 10000
        hard: 10000
    deploy:
      resources:
        reservations:
          memory: 1g
    volumes:
    - "polkadot-volume:/polkadot"


  connector-bitcoin:
    image: "analoglabs/rosetta-bitcoin"
    environment:
    - NETWORK=REGTEST
    - MODE=ONLINE
    - PORT=8080
    - "BITCOIND=http://bitcoin:18443"
    ports:
    - "8080:8080"
    depends_on:
    - bitcoin

  connector-ethereum:
    image: "analoglabs/rosetta-ethereum"
    environment:
    - NETWORK=TESTNET
    - MODE=ONLINE
    - PORT=8081
    - "GETH=http://ethereum:8545"
    ports:
    - "8081:8081"
    depends_on:
    - ethereum

  connector-polkadot:
    image: "analoglabs/rosetta-polkadot"
    command: "--network dev --url http://0.0.0.0:8082 --rpc-url ws://polkadot:9944"
    restart: always
    build:
      context: "."
      dockerfile: "./rosetta-server-polkadot/Dockerfile"
    ports:
    - "8082:8082"
    depends_on:
    - polkadot


  indexer-bitcoin:
    image: "analoglabs/rosetta-indexer"
    command: "--chain=btc --server=http://rosetta-bitcoin:8080 --url=http://0.0.0.0:8083"
    restart: always
    build:
      context: "."
      dockerfile: "./rosetta-indexer/Dockerfile"
    ports:
    - "8083:8083"
    depends_on:
    - connector-bitcoin

  indexer-ethereum:
    image: "analoglabs/rosetta-indexer"
    command: "--chain=eth --server=http://rosetta-ethereum:8081 --url=http://0.0.0.0:8084"
    restart: always
    build:
      context: "."
      dockerfile: "./rosetta-indexer/Dockerfile"
    ports:
    - "8084:8084"
    depends_on:
    - connector-ethereum

  indexer-polkadot:
    image: "analoglabs/rosetta-indexer"
    command: "--chain=dot --server=http://rosetta-polkadot:8082 --url=http://0.0.0.0:8085"
    restart: always
    build:
      context: "."
      dockerfile: "./rosetta-indexer/Dockerfile"
    ports:
    - "8085:8085"
    depends_on:
    - connector-polkadot


  explorer:
    image: "analoglabs/rosetta-explorer"
    ports:
    - "3000:3000"
    depends_on:
    - indexer-bitcoin
    - indexer-ethereum
    - indexer-polkadot
