version: "3.9"

volumes:
  bitcoin-volume:
  ethereum-volume:
  polkadot-volume:
  astar-volume:
  bitcoin-connector-volume:
  ethereum-connector-volume:
  polkadot-connector-volume:
  astar-connector-volume:

services:
  bitcoin:
    image: "ruimarinho/bitcoin-core:23"
    command: "-regtest=1 -rpcbind=0.0.0.0 -rpcport=18443 -rpcallowip=0.0.0.0/0 -rpcuser=rosetta -rpcpassword=rosetta"
    expose:
    - "18443"
    ulimits:
      nofile:
        soft: 10000
        hard: 10000
    deploy:
      resources:
        reservations:
          memory: 1g
    volumes:
    - "bitcoin-volume:/home/bitcoin/.bitcoin"

  connector-bitcoin:
    image: "analoglabs/connector-bitcoin:${IMAGE_TAG:-latest}"
    command: "--network regtest --addr 0.0.0.0:8080 --node-addr bitcoin:18443 --path /data"
    ports:
      - "8080:8080"
    depends_on:
      - bitcoin
    volumes:
      - "bitcoin-connector-volume:/data"

  ethereum:
    image: "ethereum/client-go:v1.10.26"
    command: "--dev --ipcdisable --dev.period 14 --http --http.addr 0.0.0.0 --http.vhosts * --http.api eth,debug,admin,txpool,web3"
    expose:
    - "8545"
    ulimits:
      nofile:
        soft: 10000
        hard: 10000
    deploy:
      resources:
        reservations:
          memory: 1g
    volumes:
    - "ethereum-volume:/root"

  connector-ethereum:
    image: "analoglabs/connector-ethereum:${IMAGE_TAG:-latest}"
    command: "--network dev --addr 0.0.0.0:8081 --node-addr ethereum:8545 --path /data"
    ports:
      - "8081:8081"
    depends_on:
      - ethereum
    volumes:
      - "ethereum-connector-volume:/data"

  polkadot:
    platform: linux/amd64
    image: "parity/polkadot:v0.9.37"
    command: "--chain dev --rpc-cors all --ws-port 9944 --ws-external --alice --blocks-pruning archive --state-pruning archive --base-path /polkadot"
    expose:
    - "9944"
    user: root
    ulimits:
      nofile:
        soft: 10000
        hard: 10000
    deploy:
      resources:
        reservations:
          memory: 1g
    volumes:
    - "polkadot-volume:/polkadot"

  connector-polkadot:
    image: "analoglabs/connector-polkadot:${IMAGE_TAG:-latest}"
    command: "--network dev --addr 0.0.0.0:8082 --node-addr polkadot:9944 --path /data"
    ports:
      - "8082:8082"
    depends_on:
      - polkadot
    volumes:
      - "polkadot-connector-volume:/data"
    # TODO: need to do a proper health check
    restart: always

  astar:
    platform: linux/amd64
    image: "staketechnologies/astar-collator:latest"
    command: "astar-collator --chain dev --ws-port 9994 --rpc-port 9995 --rpc-cors all --ws-external --alice --blocks-pruning archive --state-pruning archive --base-path /astar"
    expose:
    - "9994"
    - "9995"
    user: root
    ulimits:
      nofile:
        soft: 10000
        hard: 10000
    deploy:
      resources:
        reservations:
          memory: 1g
    volumes:
    - "astar-volume:/astar"

  connector-astar:
    image: "analoglabs/connector-astar:${IMAGE_TAG:-latest}"
    command: "--network dev --addr 0.0.0.0:8083 --node-addr astar:9994 --path /data"
    ports:
      - "8083:8083"
    depends_on:
      - astar
    volumes:
      - "astar-connector-volume:/data"
    # TODO: need to do a proper health check
    restart: always

  explorer:
    platform: linux/amd64
    image: "analoglabs/rosetta-explorer:latest"
    ports:
      - "3000:3000"
    depends_on:
      - connector-bitcoin
      - connector-ethereum
      - connector-polkadot
      - connector-astar
