[package]
name = "rosetta-testing-arbitrum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing="0.1.40"
rosetta-config-ethereum.workspace = true
rosetta-server-ethereum.workspace = true
rosetta-docker = { workspace = true, features = ["tests"] }
rosetta-core.workspace = true
rosetta-client.workspace = true
ethers = { version = "2.0", default-features = true, features = ["abigen", "rustls"] }
serde_json.workspace = true
rosetta-server-arbitrum.workspace = true

[dev-dependencies]
ethers-solc = "2.0"
sha3 = "0.10"