[package]
name = "rosetta-wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
async-std = { version = "1.12.0", features = ["attributes", "tokio1"] }
clap = { version = "4.0.15", features = ["derive"] }
parity-scale-codec = "3.2.1"
rosetta-client = { path = "../rosetta-client" }
rosetta-server-substrate = { path = "../rosetta-server-substrate"}
subxt = "0.24.0"
surf = { version = "2.3.2", default-features = false, features = ["h1-client-rustls"] }
tracing-subscriber = "0.3.16"
