[package]
name = "rosetta-wallet"
version = "0.4.0"
edition = "2021"
description = "Command line wallet implemented using the rosetta client."
repository = "https://github.com/analog-labs/chain-connectors"
license = "MIT"

[dependencies]
anyhow = "1.0.69"
async-std = { version = "1.12.0", features = ["attributes"] }
clap = { version = "4.1.8", features = ["derive"] }
futures = "0.3.26"
rosetta-client = { version = "0.4.0", path = "../rosetta-client" }
surf = { version = "2.3.2", default-features = false, features = ["h1-client-rustls"] }
tracing-subscriber = "0.3.16"
