/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.13
 *
 * Generated by: https://openapi-generator.tech
 */

/// BlockRequest : A BlockRequest is utilized to make a block request on the /block endpoint.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BlockRequest {
    #[serde(rename = "network_identifier")]
    pub network_identifier: crate::NetworkIdentifier,
    #[serde(rename = "block_identifier")]
    pub block_identifier: crate::PartialBlockIdentifier,
}

impl BlockRequest {
    /// A BlockRequest is utilized to make a block request on the /block endpoint.
    pub fn new(
        network_identifier: crate::NetworkIdentifier,
        block_identifier: crate::PartialBlockIdentifier,
    ) -> BlockRequest {
        BlockRequest {
            network_identifier,
            block_identifier,
        }
    }
}
