/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.13
 *
 * Generated by: https://openapi-generator.tech
 */

/// BlockTransaction : BlockTransaction contains a populated Transaction and the BlockIdentifier that contains it.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BlockTransaction {
    #[serde(rename = "block_identifier")]
    pub block_identifier: Box<crate::models::BlockIdentifier>,
    #[serde(rename = "transaction")]
    pub transaction: Box<crate::models::Transaction>,
}

impl BlockTransaction {
    /// BlockTransaction contains a populated Transaction and the BlockIdentifier that contains it.
    pub fn new(
        block_identifier: crate::models::BlockIdentifier,
        transaction: crate::models::Transaction,
    ) -> BlockTransaction {
        BlockTransaction {
            block_identifier: Box::new(block_identifier),
            transaction: Box::new(transaction),
        }
    }
}
