/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.13
 *
 * Generated by: https://openapi-generator.tech
 */

/// `BlockTransactionRequest` : A `BlockTransactionRequest` is used to fetch a Transaction included
/// in a block that is not returned in a `BlockResponse`.
#[derive(Clone, Debug, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct BlockTransactionRequest {
    #[serde(rename = "network_identifier")]
    pub network_identifier: crate::NetworkIdentifier,
    #[serde(rename = "block_identifier")]
    pub block_identifier: crate::BlockIdentifier,
    #[serde(rename = "transaction_identifier")]
    pub transaction_identifier: crate::TransactionIdentifier,
}

impl BlockTransactionRequest {
    /// A `BlockTransactionRequest` is used to fetch a Transaction included in a block that is not
    /// returned in a `BlockResponse`.
    #[must_use]
    pub const fn new(
        network_identifier: crate::NetworkIdentifier,
        block_identifier: crate::BlockIdentifier,
        transaction_identifier: crate::TransactionIdentifier,
    ) -> Self {
        Self { network_identifier, block_identifier, transaction_identifier }
    }
}
