/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.13
 *
 * Generated by: https://openapi-generator.tech
 */

/// `BlockRequest` : A `BlockRequest` is utilized to make a block request on the /block endpoint.
#[derive(Clone, Debug, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct BlockRequest {
    #[serde(rename = "block_identifier")]
    pub block_identifier: crate::PartialBlockIdentifier,
}

impl BlockRequest {
    /// A `BlockRequest` is utilized to make a block request on the /block endpoint.
    #[must_use]
    pub const fn new(block_identifier: crate::PartialBlockIdentifier) -> Self {
        Self { block_identifier }
    }
}
