/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.13
 *
 * Generated by: https://openapi-generator.tech
 */

/// `CoinIdentifier` : `CoinIdentifier` uniquely identifies a Coin.
#[derive(Clone, Debug, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct CoinIdentifier {
    /// Identifier should be populated with a globally unique identifier of a Coin. In Bitcoin,
    /// this identifier would be `transaction_hash:index`.
    #[serde(rename = "identifier")]
    pub identifier: String,
}

impl CoinIdentifier {
    /// `CoinIdentifier` uniquely identifies a Coin.
    #[must_use]
    pub const fn new(identifier: String) -> Self {
        Self { identifier }
    }
}
