/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.13
 *
 * Generated by: https://openapi-generator.tech
 */

/// Coin : Coin contains its unique identifier and the amount it represents.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Coin {
    #[serde(rename = "coin_identifier")]
    pub coin_identifier: Box<crate::models::CoinIdentifier>,
    #[serde(rename = "amount")]
    pub amount: Box<crate::models::Amount>,
}

impl Coin {
    /// Coin contains its unique identifier and the amount it represents.
    pub fn new(
        coin_identifier: crate::models::CoinIdentifier,
        amount: crate::models::Amount,
    ) -> Coin {
        Coin {
            coin_identifier: Box::new(coin_identifier),
            amount: Box::new(amount),
        }
    }
}
