/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.13
 *
 * Generated by: https://openapi-generator.tech
 */

/// `ConstructionDeriveRequest` : `ConstructionDeriveRequest` is passed to the
/// `/construction/derive` endpoint. Network is provided in the request because some blockchains
/// have different address formats for different networks. Metadata is provided in the request
/// because some blockchains allow for multiple address types (i.e. different address for validators
/// vs normal accounts).
#[derive(Clone, Debug, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct ConstructionDeriveRequest {
    #[serde(rename = "public_key")]
    pub public_key: crate::PublicKey,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
}

impl ConstructionDeriveRequest {
    /// `ConstructionDeriveRequest` is passed to the `/construction/derive` endpoint. Network is
    /// provided in the request because some blockchains have different address formats for
    /// different networks. Metadata is provided in the request because some blockchains allow for
    /// multiple address types (i.e. different address for validators vs normal accounts).
    #[must_use]
    pub const fn new(public_key: crate::PublicKey) -> Self {
        Self { public_key, metadata: None }
    }
}
