/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.13
 *
 * Generated by: https://openapi-generator.tech
 */

/// `ConstructionDeriveResponse` : `ConstructionDeriveResponse` is returned by the `/construction/derive` endpoint.

#[derive(Clone, Debug, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct ConstructionDeriveResponse {
    /// [DEPRECATED by `account_identifier` in `v1.4.4`] Address in network-specific format.
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(rename = "account_identifier", skip_serializing_if = "Option::is_none")]
    pub account_identifier: Option<crate::AccountIdentifier>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
}

impl ConstructionDeriveResponse {
    /// `ConstructionDeriveResponse` is returned by the `/construction/derive` endpoint.
    #[must_use] pub fn new() -> Self {
        Self {
            address: None,
            account_identifier: None,
            metadata: None,
        }
    }
}
