/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.13
 *
 * Generated by: https://openapi-generator.tech
 */

/// `ConstructionSubmitRequest` : The transaction submission request includes a signed transaction.
#[derive(Clone, Debug, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct ConstructionSubmitRequest {
    #[serde(rename = "signed_transaction")]
    pub signed_transaction: String,
}

impl ConstructionSubmitRequest {
    /// The transaction submission request includes a signed transaction.
    #[must_use]
    pub const fn new(signed_transaction: String) -> Self {
        Self { signed_transaction }
    }
}
