/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.13
 *
 * Generated by: https://openapi-generator.tech
 */

/// A `MempoolResponse` contains all transaction identifiers in the mempool for a particular `network_identifier`.
#[derive(Clone, Debug, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct MempoolResponse {
    #[serde(rename = "transaction_identifiers")]
    pub transaction_identifiers: Vec<crate::TransactionIdentifier>,
}

impl MempoolResponse {
    /// A `MempoolResponse` contains all transaction identifiers in the mempool for a particular `network_identifier`.
    #[must_use]
    pub const fn new(transaction_identifiers: Vec<crate::TransactionIdentifier>) -> Self {
        Self {
            transaction_identifiers,
        }
    }
}
