/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.13
 *
 * Generated by: https://openapi-generator.tech
 */

/// MempoolResponse : A MempoolResponse contains all transaction identifiers in the mempool for a particular network_identifier.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MempoolResponse {
    #[serde(rename = "transaction_identifiers")]
    pub transaction_identifiers: Vec<crate::TransactionIdentifier>,
}

impl MempoolResponse {
    /// A MempoolResponse contains all transaction identifiers in the mempool for a particular network_identifier.
    pub fn new(transaction_identifiers: Vec<crate::TransactionIdentifier>) -> MempoolResponse {
        MempoolResponse {
            transaction_identifiers,
        }
    }
}
