/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.13
 *
 * Generated by: https://openapi-generator.tech
 */

/// NetworkOptionsResponse : NetworkOptionsResponse contains information about the versioning of the node and the allowed operation statuses, operation types, and errors.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NetworkOptionsResponse {
    #[serde(rename = "version")]
    pub version: crate::Version,
    #[serde(rename = "allow")]
    pub allow: crate::Allow,
}

impl NetworkOptionsResponse {
    /// NetworkOptionsResponse contains information about the versioning of the node and the allowed operation statuses, operation types, and errors.
    pub fn new(version: crate::Version, allow: crate::Allow) -> NetworkOptionsResponse {
        NetworkOptionsResponse { version, allow }
    }
}
