/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.13
 *
 * Generated by: https://openapi-generator.tech
 */

/// `NetworkListResponse` : A `NetworkListResponse` contains all `NetworkIdentifiers` that the node can serve information for.

#[derive(Clone, Debug, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct NetworkListResponse {
    #[serde(rename = "network_identifiers")]
    pub network_identifiers: Vec<crate::NetworkIdentifier>,
}

impl NetworkListResponse {
    /// A `NetworkListResponse` contains all `NetworkIdentifiers` that the node can serve information for.
    #[must_use] pub fn new(network_identifiers: Vec<crate::NetworkIdentifier>) -> Self {
        Self {
            network_identifiers,
        }
    }
}
