/*
 * Rosetta
 *
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.13
 *
 * Generated by: https://openapi-generator.tech
 */

/// `NetworkOptionsResponse` : `NetworkOptionsResponse` contains information about the versioning of the node and the allowed operation statuses, operation types, and errors.

#[derive(Clone, Debug, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct NetworkOptionsResponse {
    #[serde(rename = "version")]
    pub version: crate::Version,
    #[serde(rename = "allow")]
    pub allow: Option<crate::Allow>,
}

impl NetworkOptionsResponse {
    /// `NetworkOptionsResponse` contains information about the versioning of the node and the allowed operation statuses, operation types, and errors.
    #[must_use] pub fn new(version: crate::Version) -> Self {
        Self {
            version,
            allow: None,
        }
    }
}
