[package]
name = "rosetta-types"
version = "0.4.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/analog-labs/chain-connectors"
description = "Rosetta API request and response structs."

[dependencies]
serde = { version = "1.0.153", features = ["derive"] }
serde_json = "1.0.94"
