[package]
name = "rosetta-types"
version = "0.5.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/analog-labs/chain-connectors"
description = "Rosetta API request and response structs."

[dependencies]
serde.workspace = true
serde_json.workspace = true
