[package]
name = "dioxus-wallet"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.66"
dioxus = "0.2.4"
dioxus-router = "0.2.3"
fermi = "0.2.1"
futures = "0.3.25"
qrcode = { git = "https://github.com/qm3ster/qrcode-rust" }
rosetta-client = { path = "../rosetta-client" }
surf = { version = "2.3.2", default-features = false, features = ["h1-client-rustls"] }
async-std = { version = "1.12.0", features = ["attributes"] }


[target.'cfg(not(target_family = "wasm"))'.dependencies]
dioxus-desktop = "0.2.3"
arboard = '3.1.1'


[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.11.1"
jni = "0.20.0"
log = "0.4.17"
ndk-context = "0.1.1"
paste = "1.0.9"
wry = "0.22.0"

[target.'cfg(target_os = "ios")'.dependencies]
bardecoder = "0.3.0"
core-graphics = "0.22.3"
core-media-sys = "0.1.2"
objc = { version = "0.2.7", features = ["exception"] }
objc-foundation = "0.1.1"
objc_id = "0.1.1"
image = { version = "0.23.14", default-features = false }

[target.'cfg(target_family = "wasm")'.dependencies]
console_error_panic_hook = "0.1.7"
dioxus-web = "0.2.1"
wasm-logger = "0.2.0"

[build-dependencies]
cc = "1.0.76"
