[package]
name = "dioxus-wallet"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dioxus = "0.2.4"
dioxus-desktop = "0.2.3"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.11.1"
log = "0.4.17"
paste = "1.0.9"
wry = { version = "0.22.0", git = "https://github.com/tauri-apps/wry", branch = "release" }
