[package]
name = "rosetta-ethereum-trie"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/analog-labs/chain-connectors"
description = "Ethereum patricia trie."

[dependencies]
ahash = { version = "0.8", default-features = false, features = ["no-rng"] }
bytes = { version = "1.5", default-features = false }
hash-db = { version = "0.16", default-features = false }
hash256-std-hasher = { version = "0.15", default-features = false }
hashbrown = { version = "0.14", default-features = false, features = ["ahash"] }
hex-literal = { version = "0.4" }
memory-db = { version = "0.32", default-features = false }
nohash-hasher = { version = "0.2.0" }
primitive-types = { version = "0.12", default-features = false, features = ["rlp"] }
rlp = { version = "0.5", default-features = false }
rlp-derive = { version = "0.1" }
schnellru = { version = "0.2", default-features = false }
tiny-keccak = { version = "2.0", features = ["keccak"] }
tracing = { version = "0.1", default-features = false }
trie-db = { version = "0.28", default-features = false }
trie-root = { version = "0.18", default-features = false }

# no_std dependencies
spin = { version = "0.9", default-features = false, features = ["once", "lock_api", "spin_mutex", "mutex", "rwlock"] }

# std dependencies
lazy_static = { version = "1.4.0", optional = true }
parking_lot = { version = "0.12", optional = true }
rand = { version = "0.8", optional = true }
thiserror = { version = "1.0", optional = true }

[dev-dependencies]
primitive-types = { version = "0.12", default-features = false, features = ["std", "rlp", "serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }

[features]
default = ["std"]
memory-db = []
std = [
  "dep:lazy_static",
  "dep:parking_lot",
  "dep:rand",
  "dep:thiserror",
  "ahash/std",
  "ahash/runtime-rng",
  "bytes/std",
  "hash-db/std",
  "hash256-std-hasher/std",
  "memory-db/std",
  "primitive-types/std",
  "rlp/std",
  "schnellru/runtime-rng",
  "tracing/std",
  "trie-db/std",
  "trie-root/std",
]
