[package]
name = "rosetta-server-substrate"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
blake2-rfc = "0.2.18"
bs58 = "0.4.0"
hex = "0.4.3"
parity-scale-codec = "3.2.1"
rosetta-types = { path = "../rosetta-types" }
ss58-registry = "1.31.0"
subxt = {git="https://github.com/Haider-Ali-DS/subxt.git", branch="haider/pallet_call_index"}
tide = "0.16.0"
tokio = { version = "1.21.2", features = ["full"] }
tracing-subscriber = "0.3.16"
smoldot = "0.4.0"
array-bytes = "4.1.0"
serde="1.0.147"
serde_json="1.0.87"