#!/bin/sh
#
# The contents of this folder except for this file are autogenerated using this script. To regenerate
# clone the rosetta specifications install the `openapi-generator` cli tool and run this script.
#
# ```sh
# git clone https://github.com/coinbase/rosetta-specifications
# cd rosetta-sdk-rust/core
# ROSETTA_SPECIFICATIONS=../../rosetta-specifications ./generate-api.sh
# ```
openapi-generator generate -i $ROSETTA_SPECIFICATIONS/api.yaml -o . -g rust-server
