[package]
name = "rosetta-server-polkadot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
async-std = { version = "1.12.0", features = ["tokio1"] }
async-trait = "0.1.64"
hex = "0.4.3"
parity-scale-codec = "3.4.0"
rosetta-config-polkadot = { version = "0.1.0", path = "../config" }
rosetta-server = { version = "0.1.0", path = "../../../rosetta-server" }
scale-info = "2.3.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
sp-keyring = "18.0.0"
subxt = "0.27.1"
tokio = { version = "1.25.0", features = ["rt-multi-thread", "macros"] }

[dev-dependencies]
rosetta-server = { version = "0.1.0", path = "../../../rosetta-server", features = ["tests"] }
