[package]
name = "rosetta-server-polkadot"
version = "0.5.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/analog-labs/chain-connectors"
description = "Polkadot rosetta server."

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
hex = "0.4"
parity-scale-codec = { workspace = true, features = ["derive"] }
rosetta-config-polkadot = { workspace = true, features = ["polkadot-metadata", "westend-metadata"] }
rosetta-core.workspace = true
rosetta-server = { workspace = true, default-features = false, features = ["ws", "webpki-tls"] }
scale-info.workspace = true
serde.workspace = true
serde_json.workspace = true
sp-keyring = "29.0"
subxt = { workspace = true, features = ["substrate-compat", "native"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing = "0.1"

[dev-dependencies]
rosetta-docker = { workspace = true, features = ["tests"] }
