[package]
name = "rosetta-config-polygon-pos"
version = "0.4.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/analog-labs/chain-connectors"
description = "Polygon configuration."

[dependencies]
anyhow = "1.0.69"
rosetta-core = { version = "0.4.0", path = "../../../rosetta-core" }
serde = { version = "1.0.153", features = ["derive"] }
