[package]
name = "rosetta-config-ethereum"
version = "0.5.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/analog-labs/chain-connectors"
description = "Ethereum configuration."

[dependencies]
anyhow = "1.0"
ethereum-types = { version = "0.14", default-features = false, features = ["rlp", "ethbloom", "codec", "num-traits"] }
rosetta-config-arbitrum.workspace = true
rosetta-config-astar = { workspace = true }
rosetta-core.workspace = true
serde.workspace = true

[features]
default = ["std"]
std = ["ethereum-types/std", "ethereum-types/serialize"]
