[package]
name = "rosetta-config-ethereum"
version = "0.5.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/analog-labs/chain-connectors"
description = "Ethereum configuration."

[dependencies]
anyhow = "1.0"
bytes = "1.5"
const-hex = "1.9"
ethereum = { version = "0.14", features = ["with-codec", "with-serde"] }
ethereum-types = { version = "0.14", features = ["codec"] }
parity-scale-codec = { workspace = true, features = ["std", "derive", "bytes"] }
rosetta-config-astar = { workspace = true }
rosetta-core.workspace = true
rosetta-ethereum-primitives = { workspace = true, features = ["std", "with-codec", "with-serde", "with-rlp", "with-crypto"] }
serde.workspace = true
thiserror = "1.0"
