[package]
name = "rosetta-config-ethereum"
version = "0.4.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/analog-labs/chain-connectors"
description = "Ethereum configuration."

[dependencies]
anyhow = "1.0"
futures-util = "0.3"
rosetta-config-astar = { version = "0.4.0", default-features = false, path = "../../astar/config" }
rosetta-core = { version = "0.4.0", path = "../../../rosetta-core" }
serde = { version = "1.0", features = ["derive"] }
