[package]
name = "rosetta-config-ethereum"
version = "0.5.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/analog-labs/chain-connectors"
description = "Ethereum configuration."

[dependencies]
anyhow = "1.0"
rosetta-config-astar = { workspace = true }
rosetta-config-arbitrum.workspace = true
rosetta-core.workspace = true
serde.workspace = true
