[package]
name = "rosetta-tx-polkadot"
version = "0.4.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/analog-labs/chain-connectors"
description = "Polkadot transaction builder."

[dependencies]
anyhow = "1.0.69"
blake2-rfc = "0.2.18"
bs58 = "0.4.0"
parity-scale-codec = { version = "3.4.0", features = ["derive"] }
rosetta-config-polkadot = { version = "0.4.0", path = "../config" }
rosetta-core = { version = "0.4.0", path = "../../../rosetta-core" }
serde_json = "1.0.94"
