[package]
name = "rosetta-tx-polkadot"
version = "0.6.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/analog-labs/chain-connectors"
description = "Polkadot transaction builder."

[dependencies]
anyhow = "1.0"
blake2-rfc = "0.2"
bs58 = "0.5"
parity-scale-codec = { workspace = true, features = ["derive"] }
rosetta-config-polkadot.workspace = true
rosetta-core.workspace = true
serde_json = "1.0"
