[package]
name = "rosetta-tx-polkadot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
blake2b_simd = "1.0.0"
parity-scale-codec = { version = "3.3.0", features = ["derive"] }
rosetta-config-polkadot = { version = "0.1.0", path = "../config" }
rosetta-core = { version = "0.1.0", path = "../../../rosetta-core" }
serde_json = "1.0.91"
sp-core = { version = "15.0.0", default-features = false, features = ["std"] }
sp-runtime = "17.0.0"
