[package]
name = "rosetta-config-bitcoin"
version = "0.5.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/analog-labs/chain-connectors"
description = "Bitcoin configuration."

[dependencies]
anyhow = "1.0"
rosetta-core.workspace = true
