[package]
name = "rosetta-config-bitcoin"
version = "0.4.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/analog-labs/chain-connectors"
description = "Bitcoin configuration."

[dependencies]
anyhow = "1.0"
rosetta-core = { version = "0.4.0", path = "../../../rosetta-core" }
