[package]
name = "rosetta-tx-polygon-pos"
version = "0.4.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/analog-labs/chain-connectors"
description = "Polygon transaction builder."

[dependencies]
anyhow = "1.0.69"
ethabi = "18.0.0"
ethers-core = "2.0.0"
rosetta-config-polygon-pos = { version = "0.4.0", path = "../config" }
rosetta-core = { version = "0.4.0", path = "../../../rosetta-core" }
serde_json = "1.0.94"
sha3 = "0.10.6"
