[package]
name = "rosetta-config-astar"
version = "0.4.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/analog-labs/chain-connectors"
description = "Polkadot configuration."

[dependencies]
anyhow = "1.0.69"
rosetta-core = { version = "0.4.0", path = "../../../rosetta-core" }
subxt = "0.29.0"
