[package]
name = "rosetta-config-astar"
version = "0.4.0"
edition = "2021"
description = "Polkadot configuration."
repository = "https://github.com/analog-labs/chain-connectors"
license = "MIT"

[dependencies]
anyhow = "1.0.69"
rosetta-core = { version = "0.4.0", path = "../../../rosetta-core" }
