[package]
name = "rosetta-config-polkadot"
version = "0.6.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/analog-labs/chain-connectors"
description = "Polkadot configuration."

[dependencies]
anyhow = "1.0"
rosetta-core.workspace = true
serde.workspace = true
subxt = { workspace = true, features = ["substrate-compat", "native"] }

[features]
default = ["polkadot-metadata", "westend-metadata", "rococo-metadata", "humanode-metadata"]
polkadot-metadata = []
westend-metadata = []
rococo-metadata = []
humanode-metadata = []