[package]
name = "rosetta-tx-ethereum"
version = "0.6.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/analog-labs/chain-connectors"
description = "Ethereum transaction builder."

[dependencies]
anyhow = "1.0"
rosetta-config-ethereum = { workspace = true, features = ["default-crypto"] }
rosetta-core.workspace = true
serde_json = "1.0"
