[package]
name = "rosetta-tx-ethereum"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
ethers-core = "2.0.0"
ethers = "2.0.0"
rosetta-config-ethereum = { version = "0.1.0", path = "../config" }
rosetta-core = { version = "0.1.0", path = "../../../rosetta-core" }
serde_json = "1.0.94"
sha3 = "0.10.6"
