[package]
name = "rosetta-server-ethereum"
version = "0.5.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/analog-labs/chain-connectors"
description = "Ethereum rosetta server."

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
ethabi = "18.0"
ethers = { version = "2.0", default-features = false, features = ["abigen", "rustls"] }
futures-timer = "3.0"
futures-util = "0.3"
hex = "0.4"
jsonrpsee = { workspace = true, features = ["macros"] }
pin-project = "1.0"
rosetta-config-ethereum.workspace = true
rosetta-core.workspace = true
rosetta-ethereum-backend = { workspace = true, features = ["std", "jsonrpsee", "with-codec", "with-serde"] }
rosetta-ethereum-rpc-client.workspace = true
rosetta-server = { workspace = true, features = ["ws", "webpki-tls"] }
serde.workspace = true
serde_json.workspace = true
thiserror = "1.0"
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing = "0.1"
url = "2.4"

[dev-dependencies]
ethers-solc = "2.0"
rosetta-client.workspace = true
rosetta-docker = { workspace = true, features = ["tests"] }
sha3 = "0.10"
