[package]
name = "rosetta-server-ethereum"
version = "0.4.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/analog-labs/chain-connectors"
description = "Ethereum rosetta server."

[dependencies]
anyhow = "1.0.69"
async-std = { version = "1.12.0", features = ["tokio1"] }
async-trait = "0.1.66"
ethabi = "18.0.0"
ethers = "2.0.2"
hex = "0.4.3"
rosetta-config-ethereum = { version = "0.4.0", path = "../config" }
rosetta-server = { version = "0.4.0", path = "../../../rosetta-server" }
serde = "1.0.153"
serde_json = "1.0"
tokio = { version = "1.26.0", features = ["rt-multi-thread", "macros"] }

[dev-dependencies]
ethers-solc = "2.0.1"
rosetta-client = { version = "0.4.0", path = "../../../rosetta-client" }
rosetta-docker = { version = "0.4.0", path = "../../../rosetta-docker" }
rosetta-server = { version = "0.4.0", path = "../../../rosetta-server", features = ["tests"] }
sha3 = "0.10.6"
