[package]
name = "rosetta-server-ethereum"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
async-std = { version = "1.12.0", features = ["tokio1"] }
async-trait = "0.1.66"
ethers = { git = "https://github.com/gakonst/ethers-rs" }
hex = "0.4.3"
rosetta-config-ethereum = { version = "0.1.0", path = "../config" }
rosetta-server = { version = "0.1.0", path = "../../../rosetta-server" }
serde = "1.0.153"
serde_json = "1.0.94"
tokio = { version = "1.26.0", features = ["rt-multi-thread", "macros"] }

[dev-dependencies]
rosetta-server = { version = "0.1.0", path = "../../../rosetta-server", features = [
    "tests",
] }
