[package]
name = "rosetta-server-ethereum"
version = "0.6.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/analog-labs/chain-connectors"
description = "Ethereum rosetta server."

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
fork-tree = { version = "13.0" }
futures-timer = "3.0"
futures-util = "0.3"
hashbrown = "0.14"
hex = "0.4"
hex-literal = "0.4"
pin-project = { version = "1.1" }
rosetta-config-ethereum.workspace = true
rosetta-core.workspace = true
rosetta-ethereum-backend = { workspace = true, features = ["jsonrpsee"] }
rosetta-server = { workspace = true, features = ["ws", "webpki-tls"] }
rosetta-utils = { workspace = true, features = ["std", "jsonrpsee"] }
serde.workspace = true
serde_json.workspace = true
thiserror = "1.0"
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing = "0.1"
url = "2.4"

[dev-dependencies]
alloy-primitives = { version = "0.7" }
alloy-sol-types = { version = "0.7" }
ethers-solc = "2.0"
rosetta-client.workspace = true
rosetta-docker = { workspace = true, features = ["tests"] }
sha3 = "0.10"
tracing-subscriber = "0.3"
