[package]
name = "rosetta-server-ethereum"
version = "0.4.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/analog-labs/chain-connectors"
description = "Ethereum rosetta server."

[dependencies]
anyhow = "1.0"
async-std = { version = "1.12", features = ["tokio1"] }
async-trait = "0.1"
ethabi = "18.0.0"
ethers = { version = "2.0", default-features = true, features = ["abigen", "rustls"] }
futures-timer = "3.0"
futures-util = "0.3"
hex = "0.4"
log = "0.4"
rosetta-config-ethereum = { version = "0.4.0", path = "../config" }
rosetta-core = { version = "0.4.0", path = "../../../rosetta-core" }
rosetta-ethereum-rpc-client = { version = "0.1.0", path = "../rpc-client" }
rosetta-server = { version = "0.4.0", path = "../../../rosetta-server", default-features = false, features = ["ws", "webpki-tls"] }
serde = "1.0"
serde_json = "1.0"
tokio = { version = "1.32", features = ["rt-multi-thread", "macros"] }
url = "2.4.0"

[dev-dependencies]
ethers-solc = "2.0.1"
rosetta-client = { version = "0.4.0", path = "../../../rosetta-client" }
rosetta-docker = { version = "0.4.0", path = "../../../rosetta-docker", features = ["tests"] }
sha3 = "0.10.6"
