[package]
name = "rosetta-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
async-trait = "0.1.66"
rosetta-crypto = { version = "0.1.0", path = "../rosetta-crypto" }
rosetta-types = { version = "0.1.0", path = "../rosetta-types" }
serde = "1.0.153"
serde_json = "1.0.94"
