[package]
name = "rosetta-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
dirs = "4.0.0"
fraction = { version = "0.12.2", default-features = false, features = ["with-bigint", "with-decimal"] }
getrandom = "0.2.8"
hex = "0.4.3"
log = "0.4.17"
rosetta-crypto = { path = "../rosetta-crypto" }
rosetta-types = { path = "../rosetta-types" }
serde = "1.0.149"
serde_json = "1.0.89"
surf = { version = "2.3.2", default-features = false }
