[package]
name = "rosetta-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
dirs = "4.0.0"
fraction = { version = "0.11.2", default-features = false, features = ["with-bigint", "with-decimal"] }
getrandom = "0.2.7"
hex = "0.4.3"
rosetta-crypto = { path = "../rosetta-crypto" }
rosetta-types = { path = "../rosetta-types" }
serde = "1.0.145"
serde_json = "1.0.86"
surf = { version = "2.3.2", default-features = false }
tracing = "0.1.37"
