[package]
name = "rosetta-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
dirs-next = "2.0.0"
fraction = { version = "0.12.2", default-features = false, features = ["with-bigint", "with-decimal"] }
getrandom = "0.2.8"
hex = "0.4.3"
log = "0.4.17"
rosetta-core = { path = "../rosetta-core" }
rosetta-crypto = { path = "../rosetta-crypto" }
rosetta-types = { path = "../rosetta-types" }
serde = "1.0.151"
serde_json = "1.0.91"
surf = { version = "2.3.2", default-features = false }

[target.'cfg(target_family = "wasm")'.dependencies]
getrandom = { version = "0.2.8", features = ["js"] }
js-sys = "0.3.60"
wasm-bindgen = "0.2.83"
web-sys = { version = "0.3.60", features = ["Storage", "Window"] }
