on:
  push:
    branches:
    - master
  pull_request:

name: rosetta-wallet

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Install rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
        targets: x86_64-unknown-linux-musl

    - name: Install dprint
      run: cargo install --locked dprint

    - name: Dprint check
      run: dprint check

    - name: cargo fmt
      run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Install rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy

    - name: cargo clippy
      run: cargo clippy --locked --workspace --examples --tests --all-features -- -D warnings

  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: cargo-deny check
        uses: EmbarkStudios/cargo-deny-action@v1

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - run: sudo add-apt-repository ppa:ethereum/ethereum
    - run: sudo apt-get update -y
    - name: Install deps
      run: sudo apt-get install -y musl-dev musl-tools solc

    - name: Install rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-musl

    - name: Build connectors
      run: ./build_connectors.sh

    - name: Pull nodes
      run: ./pull_nodes.sh

    - name: cargo test
      run: cargo test --locked --all-features --workspace
