on:
  push:
    branches:
    - master
  pull_request:

name: rosetta-wallet

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - run: sudo apt-get update
    - name: Install deps
      run: sudo apt-get install libwebkit2gtk-4.0-dev libgtk-3-dev

    - name: Install rust toolchain
      uses: hecrj/setup-rust-action@v1

    - name: cargo test
      run: cargo test --all-features --workspace

  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Install rust toolchain
      uses: hecrj/setup-rust-action@v1
      with:
        components: rustfmt

    - name: cargo fmt
      run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - run: sudo apt-get update
    - name: Install deps
      run: sudo apt-get install libwebkit2gtk-4.0-dev libgtk-3-dev

    - name: Install rust toolchain
      uses: hecrj/setup-rust-action@v1
      with:
        components: clippy

    - name: cargo clippy
      run: cargo clippy --workspace --examples --tests --all-features -- -D warnings

  dioxus-wallet:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Install llvm
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: 13
    - run: sudo ln -s llvm-ar-13 /usr/bin/llvm-ar
    - run: sudo ln -s lld-13 /usr/bin/lld

    - name: Install rust toolchain
      uses: hecrj/setup-rust-action@v1

    - name: Install xbuild
      run: cargo install xbuild --git https://github.com/cloudpeers/xbuild --branch no-flutter

    - name: Build android
      run: x build --platform android --arch arm64
      working-directory: dioxus-wallet

    - name: Build ios
      run: x build --platform ios --arch arm64
      working-directory: dioxus-wallet
