on:
  push:
    branches:
    - master

name: deploy

jobs:
  set-tags:
    name: Get & set tags
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.get-sha.outputs.sha }}
      commit_hash8: ${{ steps.get-sha.outputs.sha8 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get commit SHA
        id: get-sha
        run: |
          sha=$(git log -1 --format='%H')
          echo "sha=$sha" >> $GITHUB_OUTPUT
          echo "sha8=$(git log -1 --format='%H' | cut -c1-8)" >> $GITHUB_OUTPUT
          echo "SHA commit:" $sha

  deploy:
    runs-on: ubuntu-latest
    needs: ["set-tags"]
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Checkout sources
      uses: actions/checkout@v3

    - run: sudo apt-get update
    - name: Install deps
      run: sudo apt-get install musl-dev musl-tools

    - name: Install rust toolchain
      uses: hecrj/setup-rust-action@v1
      with:
        targets: x86_64-unknown-linux-musl

    - name: Build connector Docker images
      run: ./build_connectors.sh

    - name: Push connector images to Dockerhub
      run: ./push_connectors.sh ${{ needs.set-tags.outputs.commit_hash8 }}
