on:
  release:
    types:
    - created

name: deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Checkout sources
      uses: actions/checkout@v3

    - run: sudo apt-get update
    - name: Install deps
      run: sudo apt-get install musl-dev musl-tools

    - name: Install rust toolchain
      uses: hecrj/setup-rust-action@v1
      with:
        targets: x86_64-unknown-linux-musl

    - run: ./build_connectors.sh
    - run: ./push_connectors.sh

    - uses: withlogicco/setup-compose-cli@v1
    - run: docker context create ecs aws --from-env
    - run: docker --context=aws compose up
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

  play:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Install llvm
      run: sudo apt-get update && sudo apt-get install llvm

    - name: Install rust toolchain
      uses: hecrj/setup-rust-action@v1

    - name: Install xbuild
      uses: rust-mobile/setup-xbuild-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build android
      run: x build --platform android --arch arm64 --release
      working-directory: dioxus-wallet

    - name: Install key
      run: echo "${{ secrets.JAVA_KEYSTORE }}" | base64 -d > keystore

    - name: Sign aab
      run: jarsigner ./target/x/release/android/dioxus-wallet.aab key -keystore keystore -storepass android

    - name: Upload aab
      run: gh release upload $TAG ./target/x/release/android/dioxus-wallet.aab -R Analog-Labs/rosetta-wallet
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG: ${{ github.event.release.tag_name }}

  testflight:
    runs-on: macos-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Install llvm
      run: |
        brew install llvm
        echo "/usr/local/opt/llvm/bin" >> $GITHUB_PATH

    - name: Install rust toolchain
      uses: hecrj/setup-rust-action@v1

    - name: Install xbuild
      uses: rust-mobile/setup-xbuild-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build ios
      run: x build --platform ios --arch arm64 --release
      working-directory: dioxus-wallet
      env:
        X_PEM: ${{ secrets.X_PEM }}
        X_PROVISIONING_PROFILE: ${{ secrets.X_PROVISIONING_PROFILE }}

    - name: Install key
      run: |
        mkdir -p ~/.appstoreconnect/private_keys
        echo "${{ secrets.APPLE_KEY }}" > ~/.appstoreconnect/private_keys/AuthKey_${{ secrets.APPLE_KEY_ID }}.p8

    - name: Check ipa
      run: xcrun altool --validate-app -f ./target/x/release/ios/arm64/dioxus-wallet.ipa -t ios --apiKey ${{ secrets.APPLE_KEY_ID }} --apiIssuer ${{ secrets.APPLE_ISSUER }}

    - name: Upload ipa
      run: xcrun altool --upload-app -f ./target/x/release/ios/arm64/dioxus-wallet.ipa -t ios --apiKey ${{ secrets.APPLE_KEY_ID }} --apiIssuer ${{ secrets.APPLE_ISSUER }}
